### ISSUE TITLE
Shouldn’t the styles we provide inside the styledviews also use the respective ui styles.

### ISSUE THREAD

**Issue by xerxiastudios** [efstathiosntonas/react-native-style-libraries-benchmark#1]
For ex in nativewind.js line 10, should have used classname prop to give similar tailwind styling not the default stylesheet one. That may give us more proper benchmark.

**Comment by efstathiosntonas** [comment]
Hi @xerxiastudios, I think that according to this : https://nativewind.dev/api/styled adding `className` or use `styled` would be the same, right? I’ve never used Tailwind before so please correct me if I’m wrong.

**Comment by efstathiosntonas** [comment]
Unless you mean to use styles directly in `styled` like styled-components.

**Comment by xerxiastudios** [comment]
Yes like the styled components. Like this

`const StyledView = styled(View, 'flex-1 items-center justify-center')`

**Comment by xerxiastudios** [comment]
You can also check how tamagui guys have made their benchmarks. They used library styling for making the views which will be more proper. 

https://github.com/tamagui/tamagui/tree/24ac758bbe5d6ff2f67f25071df4286e0594f578/starters/benchmark/packages/app/features/user

**Comment by chrisarts** [comment]
I came to this from tamagui discussions Im building an alternative to NativeWind mixed a bit with styled components but I think the performance is better than original NW and SC (I made a css parser planned specially for RN but with original css features like pseudos, groups, css units etc...) im telling this to clone your repo and add my lib to see how it behavies agains the other libs here is the link if you want to check it out:
this pull will bring styled-components syntax to the lib (will be released this week)
https://github.com/react-universal/tailwind/pull/114

**Comment by efstathiosntonas** [comment]
@xerxiastudios I've updated it, now we're using `className` on the `styled` hoc.

@chrisarts can you please post a response here when the PR is merged? thanks!

**Comment by xerxiastudios** [comment]
@efstathiosntonas to get faster response from Tamagui team you should post the issue in their discord.

**Comment by efstathiosntonas** [comment]
@xerxiastudios thanks, will do!

**Comment by chrisarts** [comment]
> you please post a response here when the PR is merged? thanks!

You can use the current version of the lib, updates are applied now, still need to work on a lot of documentation around the api usage but basically its styled components for TW.

**Comment by xerxiastudios** [comment]
Closing it. All views looking good.
