### ISSUE TITLE
Updating react-native-unistyles crashes the app

### ISSUE THREAD

**Issue by atanaskanchev** [efstathiosntonas/react-native-style-libraries-benchmark#8]
Hi @efstathiosntonas I am trying to update `react-native-unistyles` to the latest `1.0.0-rc.2` but I'm getting

![image](https://github.com/efstathiosntonas/react-native-style-libraries-benchmark/assets/4958587/2b25ef54-9ad5-4ae8-9dfb-07ef5496ca06)

The latest version this works is `1.0.0-beta.5`. Do you mind trying that on your end?

**Comment by jpudysz** [comment]
I also encountered the same issue, simply re-run the metro server.
